for (let i = 0; i < 20; i++) {

    for (let j = 0; j <= 5; j++) {
        console.log(`the outer loop(i) = ${i}, the inner loop = ${j}`);
    }

}

/*
the outer loop(i) = 0, the inner loop = 0
the outer loop(i) = 0, the inner loop = 1
the outer loop(i) = 0, the inner loop = 2
the outer loop(i) = 0, the inner loop = 3
the outer loop(i) = 0, the inner loop = 4
the outer loop(i) = 0, the inner loop = 5
the outer loop(i) = 1, the inner loop = 0
the outer loop(i) = 1, the inner loop = 1
the outer loop(i) = 1, the inner loop = 2
the outer loop(i) = 1, the inner loop = 3
the outer loop(i) = 1, the inner loop = 4
the outer loop(i) = 1, the inner loop = 5
the outer loop(i) = 2, the inner loop = 0
the outer loop(i) = 2, the inner loop = 1
the outer loop(i) = 2, the inner loop = 2
the outer loop(i) = 2, the inner loop = 3
the outer loop(i) = 2, the inner loop = 4
the outer loop(i) = 2, the inner loop = 5
the outer loop(i) = 3, the inner loop = 0
the outer loop(i) = 3, the inner loop = 1
the outer loop(i) = 3, the inner loop = 2
the outer loop(i) = 3, the inner loop = 3
the outer loop(i) = 3, the inner loop = 4
the outer loop(i) = 3, the inner loop = 5
the outer loop(i) = 4, the inner loop = 0
the outer loop(i) = 4, the inner loop = 1
the outer loop(i) = 4, the inner loop = 2
the outer loop(i) = 4, the inner loop = 3
the outer loop(i) = 4, the inner loop = 4
the outer loop(i) = 4, the inner loop = 5
the outer loop(i) = 5, the inner loop = 0
the outer loop(i) = 5, the inner loop = 1
the outer loop(i) = 5, the inner loop = 2
the outer loop(i) = 5, the inner loop = 3
the outer loop(i) = 5, the inner loop = 4
the outer loop(i) = 5, the inner loop = 5
the outer loop(i) = 6, the inner loop = 0
the outer loop(i) = 6, the inner loop = 1
the outer loop(i) = 6, the inner loop = 2
the outer loop(i) = 6, the inner loop = 3
the outer loop(i) = 6, the inner loop = 4
the outer loop(i) = 6, the inner loop = 5
the outer loop(i) = 7, the inner loop = 0
the outer loop(i) = 7, the inner loop = 1
the outer loop(i) = 7, the inner loop = 2
the outer loop(i) = 7, the inner loop = 3
the outer loop(i) = 7, the inner loop = 4
the outer loop(i) = 7, the inner loop = 5
the outer loop(i) = 8, the inner loop = 0
the outer loop(i) = 8, the inner loop = 1
the outer loop(i) = 8, the inner loop = 2
the outer loop(i) = 8, the inner loop = 3
the outer loop(i) = 8, the inner loop = 4
the outer loop(i) = 8, the inner loop = 5
the outer loop(i) = 9, the inner loop = 0
the outer loop(i) = 9, the inner loop = 1
the outer loop(i) = 9, the inner loop = 2
the outer loop(i) = 9, the inner loop = 3
the outer loop(i) = 9, the inner loop = 4
the outer loop(i) = 9, the inner loop = 5
the outer loop(i) = 10, the inner loop = 0
the outer loop(i) = 10, the inner loop = 1
the outer loop(i) = 10, the inner loop = 2
the outer loop(i) = 10, the inner loop = 3
the outer loop(i) = 10, the inner loop = 4
the outer loop(i) = 10, the inner loop = 5
the outer loop(i) = 11, the inner loop = 0
the outer loop(i) = 11, the inner loop = 1
the outer loop(i) = 11, the inner loop = 2
the outer loop(i) = 11, the inner loop = 3
the outer loop(i) = 11, the inner loop = 4
the outer loop(i) = 11, the inner loop = 5
the outer loop(i) = 12, the inner loop = 0
the outer loop(i) = 12, the inner loop = 1
the outer loop(i) = 12, the inner loop = 2
the outer loop(i) = 12, the inner loop = 3
the outer loop(i) = 12, the inner loop = 4
the outer loop(i) = 12, the inner loop = 5
the outer loop(i) = 13, the inner loop = 0
the outer loop(i) = 13, the inner loop = 1
the outer loop(i) = 13, the inner loop = 2
the outer loop(i) = 13, the inner loop = 3
the outer loop(i) = 13, the inner loop = 4
the outer loop(i) = 13, the inner loop = 5
the outer loop(i) = 14, the inner loop = 0
the outer loop(i) = 14, the inner loop = 1
the outer loop(i) = 14, the inner loop = 2
the outer loop(i) = 14, the inner loop = 3
the outer loop(i) = 14, the inner loop = 4
the outer loop(i) = 14, the inner loop = 5
the outer loop(i) = 15, the inner loop = 0
the outer loop(i) = 15, the inner loop = 1
the outer loop(i) = 15, the inner loop = 2
the outer loop(i) = 15, the inner loop = 3
the outer loop(i) = 15, the inner loop = 4
the outer loop(i) = 15, the inner loop = 5
the outer loop(i) = 16, the inner loop = 0
the outer loop(i) = 16, the inner loop = 1
the outer loop(i) = 16, the inner loop = 2
the outer loop(i) = 16, the inner loop = 3
the outer loop(i) = 16, the inner loop = 4
the outer loop(i) = 16, the inner loop = 5
the outer loop(i) = 17, the inner loop = 0
the outer loop(i) = 17, the inner loop = 1
the outer loop(i) = 17, the inner loop = 2
the outer loop(i) = 17, the inner loop = 3
the outer loop(i) = 17, the inner loop = 4
the outer loop(i) = 17, the inner loop = 5
the outer loop(i) = 18, the inner loop = 0
the outer loop(i) = 18, the inner loop = 1
the outer loop(i) = 18, the inner loop = 2
the outer loop(i) = 18, the inner loop = 3
the outer loop(i) = 18, the inner loop = 4
the outer loop(i) = 18, the inner loop = 5
the outer loop(i) = 19, the inner loop = 0
the outer loop(i) = 19, the inner loop = 1
the outer loop(i) = 19, the inner loop = 2
the outer loop(i) = 19, the inner loop = 3
the outer loop(i) = 19, the inner loop = 4
the outer loop(i) = 19, the inner loop = 5
*/
